import assert from 'node:assert/strict';
import fs from 'node:fs';
const source = fs.readFileSync(new URL('../js/sensor-visuals.js', import.meta.url), 'utf8');
const { visualState, normalize } = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
assert.equal(visualState({type:'button',value:0}).active,true);
assert.equal(visualState({type:'switch',value:1}).active,false);
assert.equal(visualState({type:'touch',value:1}).active,true);
assert.equal(visualState({type:'slider',value:null}),null);
assert.equal(visualState({type:'sound',value:0,error:'sound_not_ready'}),null);
assert.equal(visualState({type:'joystick',value:{x:0,y:null}}),null);
assert.deepEqual(visualState({type:'joystick',value:{x:0,y:1}}),{mode:'xy',x:.5,y:1,level:.5,second:1});
assert.equal(visualState({type:'distance',raw:30,value:0,inMin:30,inMax:600}).level,1);
assert.equal(visualState({type:'distance',raw:600,value:1,inMin:30,inMax:600}).level,0);
assert.equal(visualState({type:'encoder',value:-90,fullRotation:360}).level,.75);
assert.equal(visualState({type:'encoder',value:720,fullRotation:360}).level,0);
assert.equal(visualState({type:'encoder',value:1,raw:10,fullRotation:0}).level,.25);
assert.equal(normalize(15,10,20),.5);
assert.equal(normalize(5,10,0),.5);
assert.equal(normalize(5,5,5),0);
assert.equal(normalize(100),1);
assert.equal(normalize(NaN),null);
console.log('Sensor mapping, active-low inputs, joystick axes, encoder wrap and invalid values: PASS');
